import fs from 'node:fs/promises';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
import {resolvePresentationFont,finalizePresentation} from '/Users/yojan/.codex/plugins/cache/openai-primary-runtime/presentations/26.904.11930/skills/presentations/container_tools/artifact_tool_utils.mjs';
const root='/Users/yojan/git/Masters-Thesis', build=root+'/presentation/.build-progress', skill='/Users/yojan/.codex/plugins/cache/openai-primary-runtime/presentations/26.904.11930/skills/presentations';
const font=resolvePresentationFont({fontFamily:'DM Sans'}); console.log('Font',font);
const p=Presentation.create({slideSize:{width:1280,height:720}});
const light='#F1F1EF',dark='#171629',muted='#73737D';
function text(s,t,x,y,w,h,size=26,bold=false,color=dark){const q=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});q.text=t;q.text.style={typeface:font,fontSize:size,bold,color,autoFit:'none'};return q;}
function line(s,x,y,w,color=dark){s.shapes.add({geometry:'rect',position:{left:x,top:y,width:w,height:2},fill:color,line:{fill:'none',width:0}});}
function slide(title,d=false){const s=p.slides.add();s.background.fill=d?dark:light;text(s,title,72,60,1136,112,48,true,d?light:dark);text(s,String(p.slides.items.length).padStart(2,'0'),1170,660,40,24,16,false,d?light:muted);return s;}
function notes(s,t,src){s.speakerNotes.textFrame.setText(t+'\n\nSources: '+src);}
function pair(s,y,name,body,d=false){line(s,72,y,1136,d?'#555463':'#D1D1D2');text(s,name,72,y+22,310,80,28,true,d?light:dark);text(s,body,420,y+22,765,95,27,false,d?light:dark);}
let s=slide('ARGOS + Terra',true);text(s,'A working foundation for\nphone-powered robot fleets',72,210,1100,220,64,true,light);text(s,'Master’s thesis progress',72,488,1000,50,30,false,light);text(s,'Yojan Gautam · October 6, 2026',72,568,1000,42,23,false,'#C4C3CD');notes(s,'This presentation summarizes the current implementation documented in the local Terra repository and the thesis materials. It presents an implementation progress report, not completed human-study findings.','Terra/README.md; Masters-Thesis/docs/ARGOS_CURRENT_SUMMARY.md');
s=slide('The research question',true);text(s,'How much local autonomy does\none operator need to supervise\na growing robot fleet?',72,210,1100,245,56,true,light);text(s,'The study will vary fleet size and autonomy level, then measure\noperator workload and mission performance.',72,510,1100,95,28,false,light);notes(s,'The central question concerns scalable human supervision. Candidate fleet sizes in the working summary are 1, 2, 4, 8 and 16, but these are proposed conditions. No comparative human-study result is claimed. The latest implementation has four named modes, which should not be confused with the older conceptual L0–L5 taxonomy.','Masters-Thesis/docs/ARGOS_CURRENT_SUMMARY.md; Terra/docs/autonomy/README.md');
s=slide('One autonomy core, two runtime adapters');
text(s,'ARGOS',72,202,330,50,36,true);text(s,'Operator control\nPer-rover authority\nProposal decisions\nSession export',72,270,330,190,27);
text(s,'Terra shared Rust core',475,202,650,50,36,true);text(s,'Depth mapping and navigation\nAuthority arbitration and safety\nVelocity control and motor output\nVersioned experiment logs',475,270,650,190,27);
line(s,72,500,1136);text(s,'Bevy / Avian simulator',72,535,500,50,30,true);text(s,'TerraPhone on iOS via UniFFI',660,535,550,50,30,true);text(s,'Zenoh connects the operator layer to rover commands and status',72,605,1100,36,23);notes(s,'Terra owns local sensing, mapping, planning, control and safety. ARGOS owns operator interaction and fleet supervision. The portable autonomy arbiter runs in both the simulator and the phone adapter. The workspace currently contains 11 Rust crates. ARGOS capability statements come from the Terra acceptance-evidence document, not a fresh inspection of its separate repository.','Terra/Cargo.toml; Terra/docs/autonomy/README.md; Terra/docs/autonomy/evidence/README.md');
s=slide('A repeatable rover simulation');s.images.add({blob:new Uint8Array(await fs.readFile('/Users/yojan/git/Terra/simulator/docs/world-preview.png')),contentType:'image/png',alt:'Terra practice-world simulator preview',fit:'contain',position:{left:72,top:210,width:690,height:388}});text(s,'Bevy + Avian',810,212,380,50,34,true);text(s,'Fleet spawning and physics\n\nDepth-derived occupancy\n\nSeeded practice environment\n\nOptional real elevation tiles',810,280,380,310,26);notes(s,'The image is the repository preview of the practice world, not the disaster-search mission. The practice square defaults to 100 m. Optional Terrarium elevation tiles provide an elevation-colored flat patch with slope obstacles, not full physical terrain or satellite imagery. Simulation rendering and fidelity follow the research question.','Terra/simulator/docs/world-preview.png; Terra/simulator/WORLD.md; Terra/README.md');
s=slide('Four implemented control modes');pair(s,190,'01  Teleoperation','The operator drives with held input. Commands expire after 500 ms.');pair(s,305,'02  Assisted teleop','The shared obstacle and braking checker filters operator intent.');pair(s,420,'03  Waypoint','Operator-selected goals use the shared follower and local planner.');pair(s,535,'04  Supervised','The rover proposes a reachable frontier. Motion requires approval.');notes(s,'All four modes use the common authority arbiter. The runtime does not automatically choose an optimal autonomy level. Supervised frontier proposals require approval and revalidation against the latest observed free map. The mode names reflect the current implementation.','Terra/docs/autonomy/README.md; Terra/docs/autonomy/evidence/README.md');
s=slide('Phone integration and shared safety');pair(s,200,'TerraPhone','Swift sensor access and controls use the Rust core through UniFFI.');pair(s,330,'Safety authority','Latched emergency stop, explicit reset, stale-input expiry and health holds.');pair(s,460,'Recording and export','The phone records sandbox JSONL logs and supports share/export.');text(s,'Physical navigation and braking still require device and chassis validation',72,613,1100,48,24,true);notes(s,'TerraPhone supports mode, stop and proposal controls. Remote-supervisor mode sends goals and intent to the simulator, avoiding a second phone waypoint controller for the same rover. Depthless devices hold map-dependent levels. Phone contact sensing is unavailable and must never appear as zero collisions. The optional phone control endpoint is loopback-only. Physical robot capability is not established by simulator or build evidence.','Terra/docs/autonomy/README.md; Terra/docs/autonomy/evidence/README.md; Terra/docs/MOBILE_CONTROL.md');
s=slide('Documented two-rover integration',true);text(s,'2 rovers',72,195,520,100,78,true,light);text(s,'4 modes exercised',650,195,560,100,60,true,light);text(s,'The saved local flow exercised held input and release, waypoint\narrival, supervised approval, and acknowledged fleet stop/takeover.',72,335,1100,115,30,false,light);line(s,72,492,1136,'#555463');text(s,'0.11–0.54 s',72,524,480,70,47,true,light);text(s,'Recorded Rust-client acknowledgement latency\nTransport/runtime timing, not native UI latency',590,525,610,90,26,false,light);notes(s,'These figures and completed actions are reported by the acceptance-evidence README for a local seed-42 two-rover run through an ARGOS Rust/Zenoh client on port 7448. The JSON evidence is described as residing in the companion ARGOS branch and was not independently rerun for this deck. A component replay and connected control flow do not establish successful operator-study trials. No comparative workload or physical-robot result is claimed.','Terra/docs/autonomy/evidence/README.md');
s=slide('The system now records study evidence');pair(s,195,'Mission scenario','Find and confirm 3 simulated survivors, then return within 600 seconds.');pair(s,320,'Experiment records','Run identity, trial assignment, effective authority, events and outcomes.');pair(s,445,'Performance measures','Mission progress, contacts, clearance episodes and operator interactions.');text(s,'Interaction counts are workload proxies. Subjective workload data is still ahead.',72,608,1136,50,24,true);notes(s,'The seed-based disaster-search world contains broken walls, a chokepoint, rubble and alternate routes. Targets remain hidden until within 5 m and the complete occupancy ray is observed free. Observing rovers must return within 2 m of the origin. These are simulation rules, not a validated survivor detector. Fixed assignment and adaptive switching are separately recorded. Complete-data recording and mission success are separate outcomes. The planned study may use NASA-TLX or a similar workload instrument.','Terra/docs/autonomy/README.md; Masters-Thesis/docs/ARGOS_CURRENT_SUMMARY.md');
s=slide('Next: validate the research question');pair(s,200,'Operator study','Run balanced fleet-size and autonomy trials across recorded scenario seeds.');pair(s,330,'Physical validation','Check phone behavior, calibrate braking and validate the real chassis.');pair(s,460,'Research extensions','Collaborative mapping, attention ranking and phone-local VLA remain future work.');text(s,'Current milestone: a shared autonomy stack with a documented fleet control flow',72,610,1136,50,24,true);notes(s,'The implementation establishes a platform for experiments. The remaining empirical work includes complete fixed/adaptive trials, subjective workload questionnaires, native device interaction checks and physical validation. The thesis repository holds the outline and Paper 1 introduction/problem-formulation drafts. Papers 2 and 3 remain placeholders. Collaborative mapping, fleet attention scheduling, natural-language commands and phone-local VLA are research directions, not completed capabilities claimed here.','Terra/docs/autonomy/evidence/README.md; Masters-Thesis/README.md; Masters-Thesis/docs/ARGOS_CURRENT_SUMMARY.md');
await (await PresentationFile.exportPptx(p)).save(build+'/candidate.pptx');
for(let i=0;i<p.slides.items.length;i++){const b=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(build+`/slide-${i+1}.png`,new Uint8Array(await b.arrayBuffer()));}
const final=root+'/presentation/output/ARGOS-Terra-Progress.pptx';
console.log(await finalizePresentation({workspaceDir:root,candidatePath:build+'/candidate.pptx',finalPath:final,pythonExecutable:'/Users/yojan/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit'],explicitTotalSlideCount:9,fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:build+'/validation.json'}));
